export const mockActivities = [
  {
    id: 'act_01',
    type: 'SYSTEM',
    content: 'New quote received from Collegio SRL — €42,000 for SS25 silk program',
    entityType: 'quote',
    entityId: 'quo_01',
    userId: 'usr_01',
    userName: 'System',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_02',
    type: 'EMAIL',
    content: 'Email opened by Lorenzo Bianchi (VBC) — FW25 suiting proposal',
    entityType: 'opportunity',
    entityId: 'opp_01',
    userId: 'usr_01',
    userName: 'Lorenzo Bianchi',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_03',
    type: 'SYSTEM',
    content: 'Swatch order delivered to Milano Office — Ref NOB-2024-0098',
    entityType: 'order',
    entityId: 'ord_05',
    userId: 'usr_01',
    userName: 'System',
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_04',
    type: 'CALL',
    content: 'Call with Ahmed Al-Rashidi re vicuña allocation — confirmed interest in 200m',
    entityType: 'opportunity',
    entityId: 'opp_05',
    userId: 'usr_01',
    userName: 'Marco Ferragamo',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_05',
    type: 'NOTE',
    content: 'Nishida selvedge denim shipment departed Osaka — tracking active',
    entityType: 'shipment',
    entityId: 'shp_01',
    userId: 'usr_01',
    userName: 'System',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_06',
    type: 'MEETING',
    content: 'Première Vision Paris — met 12 new supplier contacts, 3 qualified leads',
    entityType: 'contact',
    entityId: 'con_05',
    userId: 'usr_01',
    userName: 'Marco Ferragamo',
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_07',
    type: 'SYSTEM',
    content: 'Production update from VBC: FW25 suiting fabric weaving complete, entering finishing',
    entityType: 'order',
    entityId: 'ord_01',
    userId: 'usr_01',
    userName: 'System',
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_08',
    type: 'EMAIL',
    content: 'Sent RFQ to 3 Portuguese linen mills for SS26 development',
    entityType: 'quote',
    entityId: undefined,
    userId: 'usr_01',
    userName: 'Marco Ferragamo',
    createdAt: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
  },
]

export type MockActivity = typeof mockActivities[0]
