export const mockContacts = [
  {
    id: 'con_01',
    name: 'Marco Ferragamo',
    email: 'marco.f@luxurygroup.it',
    phone: '+39 02 00000001',
    title: 'Head of Sourcing',
    country: 'Italy',
    city: 'Milan',
    stage: 'ACTIVE',
    supplierId: 'sup_01',
    supplierName: 'Vitale Barberis Canonico',
    lastContactedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['VIP', 'Key Account'],
    notes: 'Prefers direct communication. Key decision maker for SS25 collection.',
  },
  {
    id: 'con_02',
    name: 'Claire Beaumont',
    email: 'c.beaumont@maisondebeau.fr',
    phone: '+33 1 00000002',
    title: 'Fabric Director',
    country: 'France',
    city: 'Paris',
    stage: 'ACTIVE',
    supplierId: 'sup_03',
    supplierName: 'Bouchier Textiles',
    lastContactedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['Key Account'],
    notes: 'Interested in exclusive jersey compositions for RTW.',
  },
  {
    id: 'con_03',
    name: 'Leon Draper',
    email: 'leon@draper-sourcing.co.uk',
    phone: '+44 20 00000003',
    title: 'Procurement Director',
    country: 'UK',
    city: 'London',
    stage: 'PROSPECT',
    supplierId: 'sup_04',
    supplierName: 'GB Textiles Ltd',
    lastContactedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['New Lead'],
    notes: 'Connected through Bradford Textile Society. Looking for tweed suppliers.',
  },
  {
    id: 'con_04',
    name: 'Yuki Tanaka',
    email: 'y.tanaka@premium-brands.jp',
    phone: '+81 3 0000 0004',
    title: 'Textile Sourcing Manager',
    country: 'Japan',
    city: 'Tokyo',
    stage: 'ACTIVE',
    supplierId: 'sup_07',
    supplierName: 'Nishida Textile Co.',
    lastContactedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['VIP', 'Key Account', 'Denim'],
    notes: 'Exclusive partnership for selvedge denim. Annual volume 5,000m+',
  },
  {
    id: 'con_05',
    name: 'Sofia Rodriguez',
    email: 'sofia@modapremium.es',
    phone: '+34 91 000 0005',
    title: 'Design & Sourcing',
    country: 'Spain',
    city: 'Barcelona',
    stage: 'LEAD',
    supplierId: undefined,
    supplierName: undefined,
    lastContactedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['New Lead'],
    notes: 'Met at Première Vision Paris. Interest in sustainable luxury fabrics.',
  },
  {
    id: 'con_06',
    name: 'Ahmed Al-Rashidi',
    email: 'a.rashidi@khalijfashion.ae',
    phone: '+971 4 000 0006',
    title: 'CEO',
    country: 'UAE',
    city: 'Dubai',
    stage: 'NEGOTIATION',
    supplierId: 'sup_02',
    supplierName: 'Loro Piana Fibre',
    lastContactedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['VIP', 'High Value'],
    notes: 'Annual fabric budget $2M+. Focus on vicuña and baby cashmere.',
  },
]

export type MockContact = typeof mockContacts[0]
