export const mockFabrics = [
  {
    id: 'fab_01',
    sku: 'VBC-SW-001',
    name: 'Superfine Merino Suiting',
    supplierId: 'sup_01',
    supplierName: 'Vitale Barberis Canonico',
    supplierCountry: 'Italy',
    fiberContent: [{ fiber: 'Merino Wool', percentage: 100 }],
    weightGsm: 220,
    widthCm: 150,
    weaveType: 'TWILL',
    finish: 'Milled',
    stretch: false,
    seasonality: ['FW', 'All Season'],
    colors: ['Charcoal', 'Navy', 'Mid Grey', 'Camel'],
    pricePerMeter: 52,
    currency: 'EUR',
    moqMeters: 300,
    leadTimeDays: 45,
    stockMeters: 1200,
    isActive: true,
    certifications: ['Woolmark', 'OEKO-TEX Standard 100'],
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'],
    sustainabilityScore: 82,
    description: 'Super 130s merino wool in classic suiting weight. Perfect for bespoke tailoring and luxury ready-to-wear.',
  },
  {
    id: 'fab_02',
    sku: 'LP-VC-001',
    name: 'Baby Cashmere Coating',
    supplierId: 'sup_02',
    supplierName: 'Loro Piana Fibre',
    supplierCountry: 'Italy',
    fiberContent: [{ fiber: 'Baby Cashmere', percentage: 100 }],
    weightGsm: 380,
    widthCm: 150,
    weaveType: 'PLAIN',
    finish: 'Brushed',
    stretch: false,
    seasonality: ['FW'],
    colors: ['Ivory', 'Camel', 'Chocolate', 'Dove Grey'],
    pricePerMeter: 320,
    currency: 'EUR',
    moqMeters: 500,
    leadTimeDays: 60,
    stockMeters: 450,
    isActive: true,
    certifications: ['Woolmark', 'GOTS'],
    images: ['https://images.unsplash.com/photo-1571513800374-df1bbe650e56?w=600&q=80'],
    sustainabilityScore: 91,
    description: 'Exceptionally soft baby cashmere coating from Hircus goats. The pinnacle of luxury outerwear fabric.',
  },
  {
    id: 'fab_03',
    sku: 'BT-JK-003',
    name: 'Silk-Wool Jersey',
    supplierId: 'sup_03',
    supplierName: 'Bouchier Textiles',
    supplierCountry: 'France',
    fiberContent: [
      { fiber: 'Merino Wool', percentage: 60 },
      { fiber: 'Silk', percentage: 40 },
    ],
    weightGsm: 180,
    widthCm: 165,
    weaveType: 'JERSEY',
    finish: 'Soft Hand',
    stretch: true,
    seasonality: ['SS', 'FW', 'All Season'],
    colors: ['Black', 'White', 'Ecru', 'Midnight Blue', 'Blush'],
    pricePerMeter: 38,
    currency: 'EUR',
    moqMeters: 200,
    leadTimeDays: 30,
    stockMeters: 800,
    isActive: true,
    certifications: ['OEKO-TEX Standard 100', 'bluesign'],
    images: ['https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=80'],
    sustainabilityScore: 75,
    description: 'Fluid silk-wool jersey with exceptional drape. Versatile for day-to-evening wear.',
  },
  {
    id: 'fab_04',
    sku: 'GB-TW-007',
    name: 'Yorkshire Worsted Tweed',
    supplierId: 'sup_04',
    supplierName: 'GB Textiles Ltd',
    supplierCountry: 'UK',
    fiberContent: [
      { fiber: 'Wool', percentage: 75 },
      { fiber: 'Mohair', percentage: 25 },
    ],
    weightGsm: 310,
    widthCm: 150,
    weaveType: 'TWILL',
    finish: 'Natural',
    stretch: false,
    seasonality: ['FW'],
    colors: ['Natural Heather', 'Forest Green', 'Navy', 'Rust'],
    pricePerMeter: 42,
    currency: 'GBP',
    moqMeters: 250,
    leadTimeDays: 35,
    stockMeters: 600,
    isActive: true,
    certifications: ['Woolmark', 'ISO 9001'],
    images: ['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80'],
    sustainabilityScore: 68,
    description: 'Classic Yorkshire worsted tweed with mohair sheen. The quintessential fabric for British country and city tailoring.',
  },
  {
    id: 'fab_05',
    sku: 'ALB-CO-012',
    name: 'Egyptian Giza 87 Poplin',
    supplierId: 'sup_05',
    supplierName: 'Albaz Fabric House',
    supplierCountry: 'Turkey',
    fiberContent: [{ fiber: 'Egyptian Cotton', percentage: 100 }],
    weightGsm: 115,
    widthCm: 145,
    weaveType: 'PLAIN',
    finish: 'Mercerized',
    stretch: false,
    seasonality: ['SS', 'All Season'],
    colors: ['White', 'Sky Blue', 'Pink', 'Ecru', 'Lavender', 'Striped'],
    pricePerMeter: 11,
    currency: 'USD',
    moqMeters: 100,
    leadTimeDays: 21,
    stockMeters: 3500,
    isActive: true,
    certifications: ['GOTS', 'OEKO-TEX Standard 100', 'Fair Trade'],
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'],
    sustainabilityScore: 79,
    description: 'Two-ply Giza 87 cotton poplin with exceptional hand feel and lustrous finish. Premium shirting foundation.',
  },
  {
    id: 'fab_06',
    sku: 'MC-SJ-004',
    name: 'Como Silk Jacquard',
    supplierId: 'sup_06',
    supplierName: 'Milan Collection Srl',
    supplierCountry: 'Italy',
    fiberContent: [{ fiber: 'Mulberry Silk', percentage: 100 }],
    weightGsm: 95,
    widthCm: 140,
    weaveType: 'JACQUARD',
    finish: 'Calendered',
    stretch: false,
    seasonality: ['SS', 'Resort'],
    colors: ['Ivory', 'Champagne', 'Rose Gold', 'Midnight'],
    pricePerMeter: 145,
    currency: 'EUR',
    moqMeters: 150,
    leadTimeDays: 28,
    stockMeters: 280,
    isActive: true,
    certifications: ['ISO 9001', 'OEKO-TEX Standard 100'],
    images: ['https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=80'],
    sustainabilityScore: 65,
    description: 'Intricate Como silk jacquard with floral motif. Made on historic Jacquard looms for maximum intricacy and definition.',
  },
  {
    id: 'fab_07',
    sku: 'NS-SD-002',
    name: 'Selvedge Denim 14oz',
    supplierId: 'sup_07',
    supplierName: 'Nishida Textile Co.',
    supplierCountry: 'Japan',
    fiberContent: [{ fiber: 'Cotton', percentage: 100 }],
    weightGsm: 476,
    widthCm: 76,
    weaveType: 'TWILL',
    finish: 'Sanforized',
    stretch: false,
    seasonality: ['FW', 'All Season'],
    colors: ['Indigo', 'Black x Black', 'Grey', 'Raw'],
    pricePerMeter: 78,
    currency: 'USD',
    moqMeters: 300,
    leadTimeDays: 50,
    stockMeters: 420,
    isActive: true,
    certifications: ['OEKO-TEX Standard 100'],
    images: ['https://images.unsplash.com/photo-1589136777260-5c8b87beff5e?w=600&q=80'],
    sustainabilityScore: 72,
    description: 'Authentic 14oz Japanese selvedge denim woven on vintage shuttle looms. Prized by premium denim brands globally.',
  },
  {
    id: 'fab_08',
    sku: 'INC-BA-001',
    name: 'Royal Baby Alpaca',
    supplierId: 'sup_08',
    supplierName: 'Incatops SA',
    supplierCountry: 'Peru',
    fiberContent: [{ fiber: 'Baby Alpaca', percentage: 100 }],
    weightGsm: 265,
    widthCm: 150,
    weaveType: 'PLAIN',
    finish: 'Brushed',
    stretch: false,
    seasonality: ['FW', 'Resort'],
    colors: ['Natural White', 'Natural Brown', 'Sage', 'Dusty Rose', 'Charcoal'],
    pricePerMeter: 85,
    currency: 'USD',
    moqMeters: 200,
    leadTimeDays: 55,
    stockMeters: 350,
    isActive: true,
    certifications: ['GOTS', 'Woolmark', 'Fair Trade', 'B Corp'],
    images: ['https://images.unsplash.com/photo-1528396518501-b53b655eb9b3?w=600&q=80'],
    sustainabilityScore: 94,
    description: 'Certified baby alpaca from Peruvian highlands with full traceability from fibre to fabric. Lighter than cashmere, softer than merino.',
  },
]

export type MockFabric = typeof mockFabrics[0]
