export const mockOpportunities = [
  {
    id: 'opp_01',
    title: 'Italian Luxury Collection FW25',
    supplierId: 'sup_01',
    supplierName: 'Vitale Barberis Canonico',
    supplierCountry: 'Italy',
    contactId: 'con_01',
    contactName: 'Marco Ferragamo',
    value: 320000,
    currency: 'EUR',
    stage: 'NEGOTIATION',
    probability: 60,
    expectedCloseDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['FW25', 'Wool', 'Premium'],
    notes: 'Suiting fabrics for FW25 men\'s collection. 3,000m minimum.',
  },
  {
    id: 'opp_02',
    title: 'Premium Worsted Program',
    supplierId: 'sup_04',
    supplierName: 'GB Textiles Ltd',
    supplierCountry: 'UK',
    contactId: 'con_03',
    contactName: 'Leon Draper',
    value: 140000,
    currency: 'GBP',
    stage: 'SAMPLING',
    probability: 25,
    expectedCloseDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['FW25', 'Worsted', 'Tweed'],
    notes: 'Sampling 8 colorways for SS25 tweed capsule.',
  },
  {
    id: 'opp_03',
    title: 'Spring Summer 2025 — Silk Program',
    supplierId: 'sup_06',
    supplierName: 'Milan Collection Srl',
    supplierCountry: 'Italy',
    contactId: 'con_01',
    contactName: 'Marco Ferragamo',
    value: 125000,
    currency: 'EUR',
    stage: 'PRODUCTION',
    probability: 80,
    expectedCloseDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['SS25', 'Silk', 'Jacquard'],
    notes: 'Como silk jacquard in production. 1,200m x 5 colorways.',
  },
  {
    id: 'opp_04',
    title: 'Baby Alpaca Capsule — Resort',
    supplierId: 'sup_08',
    supplierName: 'Incatops SA',
    supplierCountry: 'Peru',
    contactId: 'con_05',
    contactName: 'Sofia Rodriguez',
    value: 88000,
    currency: 'USD',
    stage: 'QUOTATION',
    probability: 40,
    expectedCloseDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['Resort25', 'Alpaca', 'Sustainable'],
    notes: 'Sustainable baby alpaca for resort collection. Quote requested.',
  },
  {
    id: 'opp_05',
    title: 'Vicuña Exclusive — Ultra Luxury',
    supplierId: 'sup_02',
    supplierName: 'Loro Piana Fibre',
    supplierCountry: 'Italy',
    contactId: 'con_06',
    contactName: 'Ahmed Al-Rashidi',
    value: 850000,
    currency: 'EUR',
    stage: 'NEGOTIATION',
    probability: 55,
    expectedCloseDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['FW25', 'Vicuña', 'Ultra Premium', 'Exclusive'],
    notes: 'Exclusive vicuña allocation for Middle East luxury brand. High priority.',
  },
  {
    id: 'opp_06',
    title: 'Japanese Selvedge Denim — Heritage Line',
    supplierId: 'sup_07',
    supplierName: 'Nishida Textile Co.',
    supplierCountry: 'Japan',
    contactId: 'con_04',
    contactName: 'Yuki Tanaka',
    value: 215000,
    currency: 'USD',
    stage: 'SHIPMENT',
    probability: 90,
    expectedCloseDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['SS25', 'Denim', 'Heritage'],
    notes: 'Final shipment from Osaka port. Tracking in progress.',
  },
  {
    id: 'opp_07',
    title: 'French Jersey RTW Program',
    supplierId: 'sup_03',
    supplierName: 'Bouchier Textiles',
    supplierCountry: 'France',
    contactId: 'con_02',
    contactName: 'Claire Beaumont',
    value: 175000,
    currency: 'EUR',
    stage: 'DISCOVERY',
    probability: 10,
    expectedCloseDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['FW25', 'Jersey', 'RTW'],
    notes: 'Initial discovery call completed. Sending fabric library next week.',
  },
  {
    id: 'opp_08',
    title: 'India Cotton Shirting — Core Program',
    supplierId: 'sup_10',
    supplierName: 'Arvind Limited',
    supplierCountry: 'India',
    contactId: undefined,
    contactName: undefined,
    value: 95000,
    currency: 'USD',
    stage: 'COMPLETED',
    probability: 100,
    expectedCloseDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['SS24', 'Cotton', 'Shirting'],
    notes: 'Delivered and approved. Renewing for SS25.',
  },
]

export type MockOpportunity = typeof mockOpportunities[0]
