export const mockOrders = [
  {
    id: 'ord_01',
    orderNo: 'NOB-2025-0142',
    title: 'VBC Superfine Merino — FW25 Collection',
    supplierId: 'sup_01',
    supplierName: 'Vitale Barberis Canonico',
    supplierCountry: 'Italy',
    status: 'PRODUCTION',
    totalValue: 156000,
    currency: 'EUR',
    incoterm: 'FOB',
    deliveryDate: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { description: 'Super 130s Charcoal Twill 2/2', quantity: 800, unit: 'meters', unitPrice: 52, totalPrice: 41600 },
      { description: 'Super 130s Navy Twill 2/2', quantity: 800, unit: 'meters', unitPrice: 52, totalPrice: 41600 },
      { description: 'Super 130s Mid Grey Plain', quantity: 600, unit: 'meters', unitPrice: 52, totalPrice: 31200 },
      { description: 'Camel Hair Blend Coating', quantity: 800, unit: 'meters', unitPrice: 52, totalPrice: 41600 },
    ],
    poReference: 'PO-2025-FW25-001',
  },
  {
    id: 'ord_02',
    orderNo: 'NOB-2025-0138',
    title: 'Como Silk Jacquard — SS25',
    supplierId: 'sup_06',
    supplierName: 'Milan Collection Srl',
    supplierCountry: 'Italy',
    status: 'PACKING',
    totalValue: 87000,
    currency: 'EUR',
    incoterm: 'CIF',
    deliveryDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { description: 'Ivory Silk Jacquard Floral', quantity: 200, unit: 'meters', unitPrice: 145, totalPrice: 29000 },
      { description: 'Champagne Silk Jacquard Geo', quantity: 200, unit: 'meters', unitPrice: 145, totalPrice: 29000 },
      { description: 'Rose Gold Silk Jacquard', quantity: 200, unit: 'meters', unitPrice: 145, totalPrice: 29000 },
    ],
    poReference: 'PO-2025-SS25-003',
  },
  {
    id: 'ord_03',
    orderNo: 'NOB-2025-0129',
    title: 'Japanese Selvedge 14oz — Heritage',
    supplierId: 'sup_07',
    supplierName: 'Nishida Textile Co.',
    supplierCountry: 'Japan',
    status: 'SHIPPED',
    totalValue: 156000,
    currency: 'USD',
    incoterm: 'FOB',
    deliveryDate: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { description: 'Raw Indigo Selvedge 14oz', quantity: 600, unit: 'meters', unitPrice: 78, totalPrice: 46800 },
      { description: 'Black x Black Selvedge', quantity: 400, unit: 'meters', unitPrice: 78, totalPrice: 31200 },
      { description: 'Grey Cast Selvedge', quantity: 400, unit: 'meters', unitPrice: 78, totalPrice: 31200 },
    ],
    poReference: 'PO-2025-SS25-007',
  },
  {
    id: 'ord_04',
    orderNo: 'NOB-2025-0115',
    title: 'Baby Alpaca Knitwear Fabric',
    supplierId: 'sup_08',
    supplierName: 'Incatops SA',
    supplierCountry: 'Peru',
    status: 'CONFIRMED',
    totalValue: 42500,
    currency: 'USD',
    incoterm: 'EXW',
    deliveryDate: new Date(Date.now() + 55 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { description: 'Natural White Baby Alpaca', quantity: 250, unit: 'meters', unitPrice: 85, totalPrice: 21250 },
      { description: 'Natural Brown Baby Alpaca', quantity: 250, unit: 'meters', unitPrice: 85, totalPrice: 21250 },
    ],
    poReference: 'PO-2025-FW25-009',
  },
  {
    id: 'ord_05',
    orderNo: 'NOB-2024-0098',
    title: 'Indian Poplin — Core Shirting',
    supplierId: 'sup_10',
    supplierName: 'Arvind Limited',
    supplierCountry: 'India',
    status: 'DELIVERED',
    totalValue: 24500,
    currency: 'USD',
    incoterm: 'DDP',
    deliveryDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { description: 'White Poplin 2-ply', quantity: 1000, unit: 'meters', unitPrice: 8.5, totalPrice: 8500 },
      { description: 'Sky Blue Poplin 2-ply', quantity: 800, unit: 'meters', unitPrice: 8.5, totalPrice: 6800 },
      { description: 'Pink Poplin 2-ply', quantity: 800, unit: 'meters', unitPrice: 8.5, totalPrice: 6800 },
      { description: 'Ecru Poplin 2-ply', quantity: 280, unit: 'meters', unitPrice: 8.5, totalPrice: 2380 },
    ],
    poReference: 'PO-2024-SS24-012',
  },
]

export type MockOrder = typeof mockOrders[0]
