export const mockSuppliers = [
  {
    id: 'sup_01',
    name: 'Vitale Barberis Canonico',
    country: 'Italy',
    city: 'Pratrivero',
    region: 'Piedmont',
    type: 'MILL',
    tier: 'TIER1',
    specialties: ['Superfine Wool', 'Cashmere Blend', 'Formal Suiting'],
    certifications: ['Woolmark', 'OEKO-TEX Standard 100', 'ISO 9001'],
    moqMeters: 300,
    leadTimeDays: 45,
    priceRangeMin: 28,
    priceRangeMax: 85,
    currency: 'EUR',
    rating: 4.9,
    isVerified: true,
    isActive: true,
    website: 'https://vbc1663.com',
    email: 'sourcing@vbc1663.com',
    phone: '+39 015 7456600',
    profileImage: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=400&q=80',
    description: 'Founded in 1663, Vitale Barberis Canonico is one of the oldest and most prestigious wool mills in the world, producing the finest suiting fabrics for luxury fashion houses.',
  },
  {
    id: 'sup_02',
    name: 'Loro Piana Fibre',
    country: 'Italy',
    city: 'Quarona',
    region: 'Piedmont',
    type: 'MILL',
    tier: 'TIER1',
    specialties: ['Vicuña', 'Baby Cashmere', 'Superfine Merino'],
    certifications: ['Woolmark', 'GOTS', 'Cradle to Cradle'],
    moqMeters: 500,
    leadTimeDays: 60,
    priceRangeMin: 120,
    priceRangeMax: 850,
    currency: 'EUR',
    rating: 5.0,
    isVerified: true,
    isActive: true,
    website: 'https://loropiana.com',
    email: 'b2b@loropiana.com',
    phone: '+39 0163 44111',
    profileImage: 'https://images.unsplash.com/photo-1571513800374-df1bbe650e56?w=400&q=80',
    description: 'The world\'s premier luxury fibre company, known for vicuña, baby cashmere, and the finest merino wools sourced from Australasia and South America.',
  },
  {
    id: 'sup_03',
    name: 'Bouchier Textiles',
    country: 'France',
    city: 'Troyes',
    region: 'Grand Est',
    type: 'MILL',
    tier: 'TIER1',
    specialties: ['Jersey', 'Fine Knits', 'Technical Fabrics'],
    certifications: ['OEKO-TEX Standard 100', 'bluesign', 'ISO 14001'],
    moqMeters: 200,
    leadTimeDays: 30,
    priceRangeMin: 22,
    priceRangeMax: 65,
    currency: 'EUR',
    rating: 4.7,
    isVerified: true,
    isActive: true,
    website: 'https://bouchier-textiles.fr',
    email: 'contact@bouchier-textiles.fr',
    phone: '+33 3 25 72 00 00',
    profileImage: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=400&q=80',
    description: 'Specialist in fine jersey and knit fabrics for luxury ready-to-wear and sportswear. Trusted by Hermès, Chanel, and Givenchy.',
  },
  {
    id: 'sup_04',
    name: 'GB Textiles Ltd',
    country: 'UK',
    city: 'Bradford',
    region: 'Yorkshire',
    type: 'MILL',
    tier: 'TIER2',
    specialties: ['Worsted Wool', 'Tweed', 'Harris Tweed'],
    certifications: ['Woolmark', 'ISO 9001'],
    moqMeters: 250,
    leadTimeDays: 35,
    priceRangeMin: 18,
    priceRangeMax: 55,
    currency: 'GBP',
    rating: 4.5,
    isVerified: true,
    isActive: true,
    website: 'https://gbtextiles.co.uk',
    email: 'trade@gbtextiles.co.uk',
    phone: '+44 1274 000000',
    profileImage: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&q=80',
    description: 'Heritage British wool mill producing world-class worsted wools and tweeds for fashion houses and tailoring brands globally.',
  },
  {
    id: 'sup_05',
    name: 'Albaz Fabric House',
    country: 'Turkey',
    city: 'Istanbul',
    region: 'Marmara',
    type: 'TRADER',
    tier: 'TIER2',
    specialties: ['Cotton Shirting', 'Poplin', 'Oxford Cloth', 'Denim'],
    certifications: ['GOTS', 'OEKO-TEX Standard 100', 'Fair Trade'],
    moqMeters: 100,
    leadTimeDays: 21,
    priceRangeMin: 4,
    priceRangeMax: 18,
    currency: 'USD',
    rating: 4.3,
    isVerified: true,
    isActive: true,
    website: 'https://albazfabric.com',
    email: 'trade@albazfabric.com',
    phone: '+90 212 000 0000',
    profileImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    description: 'Premium cotton fabric trader sourcing the finest Egyptian and Supima cotton shirting materials at competitive prices.',
  },
  {
    id: 'sup_06',
    name: 'Milan Collection Srl',
    country: 'Italy',
    city: 'Milan',
    region: 'Lombardy',
    type: 'AGENT',
    tier: 'TIER1',
    specialties: ['Silk', 'Jacquard', 'Embroidered Fabrics'],
    certifications: ['ISO 9001', 'OEKO-TEX Standard 100'],
    moqMeters: 150,
    leadTimeDays: 28,
    priceRangeMin: 35,
    priceRangeMax: 180,
    currency: 'EUR',
    rating: 4.8,
    isVerified: true,
    isActive: true,
    website: 'https://milancollection.it',
    email: 'sourcing@milancollection.it',
    phone: '+39 02 00000000',
    profileImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&q=80',
    description: 'Curated sourcing agent specializing in Como silk and luxury jacquard fabrics from Italy\'s most prestigious mills.',
  },
  {
    id: 'sup_07',
    name: 'Nishida Textile Co.',
    country: 'Japan',
    city: 'Nishiwaki',
    region: 'Hyogo',
    type: 'MILL',
    tier: 'TIER1',
    specialties: ['Denim', 'Selvedge', 'Technical Wovens'],
    certifications: ['OEKO-TEX Standard 100', 'ISO 14001'],
    moqMeters: 300,
    leadTimeDays: 50,
    priceRangeMin: 45,
    priceRangeMax: 120,
    currency: 'JPY',
    rating: 4.9,
    isVerified: true,
    isActive: true,
    website: 'https://nishida-textile.jp',
    email: 'export@nishida-textile.jp',
    phone: '+81 795 00 0000',
    profileImage: 'https://images.unsplash.com/photo-1589136777260-5c8b87beff5e?w=400&q=80',
    description: 'Japanese mill producing the world\'s finest selvedge denim and technical wovens using traditional shuttle looms.',
  },
  {
    id: 'sup_08',
    name: 'Incatops SA',
    country: 'Peru',
    city: 'Arequipa',
    region: 'Arequipa',
    type: 'MILL',
    tier: 'TIER2',
    specialties: ['Alpaca', 'Baby Alpaca', 'Pima Cotton'],
    certifications: ['GOTS', 'Woolmark', 'Fair Trade', 'B Corp'],
    moqMeters: 200,
    leadTimeDays: 55,
    priceRangeMin: 25,
    priceRangeMax: 95,
    currency: 'USD',
    rating: 4.7,
    isVerified: true,
    isActive: true,
    website: 'https://incatops.com',
    email: 'exports@incatops.com',
    phone: '+51 54 000000',
    profileImage: 'https://images.unsplash.com/photo-1528396518501-b53b655eb9b3?w=400&q=80',
    description: 'Leading producer of luxury alpaca and baby alpaca fabrics from the Peruvian highlands, with full supply chain traceability.',
  },
  {
    id: 'sup_09',
    name: 'Ardalanish Isle of Mull Weavers',
    country: 'UK',
    city: 'Isle of Mull',
    region: 'Scotland',
    type: 'MILL',
    tier: 'TIER2',
    specialties: ['Harris Tweed', 'Heritage Wool', 'Tartan'],
    certifications: ['Woolmark', 'GOTS'],
    moqMeters: 100,
    leadTimeDays: 40,
    priceRangeMin: 40,
    priceRangeMax: 110,
    currency: 'GBP',
    rating: 4.6,
    isVerified: false,
    isActive: true,
    website: 'https://ardalanish.com',
    email: 'info@ardalanish.com',
    phone: '+44 1681 700 265',
    profileImage: 'https://images.unsplash.com/photo-1559583985-c80d8ad9b29f?w=400&q=80',
    description: 'Artisan Scottish weavers producing limited-edition tweeds and heritage wools using traditional hand-loom techniques.',
  },
  {
    id: 'sup_10',
    name: 'Arvind Limited',
    country: 'India',
    city: 'Ahmedabad',
    region: 'Gujarat',
    type: 'FACTORY',
    tier: 'TIER2',
    specialties: ['Denim', 'Woven Fabric', 'Technical Textiles', 'Sustainable Fabrics'],
    certifications: ['GOTS', 'OEKO-TEX Standard 100', 'bluesign', 'ISO 9001', 'ISO 14001'],
    moqMeters: 500,
    leadTimeDays: 25,
    priceRangeMin: 3,
    priceRangeMax: 22,
    currency: 'USD',
    rating: 4.4,
    isVerified: true,
    isActive: true,
    website: 'https://arvind.com',
    email: 'sourcing@arvind.com',
    phone: '+91 79 6600 0000',
    profileImage: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400&q=80',
    description: 'India\'s largest denim manufacturer and one of Asia\'s premier fabric conglomerates, producing 100+ million meters annually.',
  },
]

export type MockSupplier = typeof mockSuppliers[0]
